kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: api
  labels:
    app: datadashboard
    cheese: stilton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadashboard
      task: api
  template:
    metadata:
      labels:
        app: datadashboard
        task: api
        version: v0.0.1
    spec:
      containers:
      - name: api
        image: 616488335016.dkr.ecr.ap-south-1.amazonaws.com/api:latest
      imagePullSecrets:
      - name: ecr-registry-secret
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - name: http
    targetPort: 5000
    port: 80
  selector:
    app: datadashboard
    task: api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: datadashboard
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: dd.minikube
    http:
      paths:
      - path: /
        backend:
          serviceName: api
          servicePort: http
